# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Samuel Ochoa
email: samuelochoap@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Samuel Ochoa, software developer and information systems engineer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://s8a.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: S8A
repository: S8A/s8a.github.io
author:
  name: Samuel Ochoa
  email: samuelochoap@gmail.com
  url: https://s8a.github.io
  twitter: SamuelOchoaP

permalink: /:year/:month/:day/:title/

paginate: 12
paginate_path: "/blog/:num/"

collections:
  documents:
    output: true
    permalink: /:collection/:name/
  programs:
    output: true
    permalink: /:collection/:name/
  websites:
    output: true
    permalink: /:collection/:name/
  open_source:
    output: true
    permalink: /:collection/:name/

# Build settings
markdown: kramdown
# Don't set plugins because all of them are set in the jekyll_plugins
# group of the Gemfile

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docker-compose.yml

# Front Matter defaults
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/s8a-thumbnail.webp
