# Site settings
title: Samuel Ochoa
email: samuelochoap@gmail.com
description: >-
  Samuel Ochoa, software developer and information systems engineer.
baseurl: ""
url: "https://s8a.github.io"
github_username: S8A
repository: S8A/s8a.github.io
author:
  name: Samuel Ochoa
  email: samuelochoap@gmail.com
  url: https://s8a.github.io
  twitter: SamuelOchoaP

permalink: /:year/:month/:day/:title/

paginate: 12
paginate_path: "/blog/:num/"

collections:
  documents:
    output: true
    permalink: /:collection/:name/
  programs:
    output: true
    permalink: /:collection/:name/
  websites:
    output: true
    permalink: /:collection/:name/
  open_source:
    output: true
    permalink: /open-source/:name/
  misc_projects:
    output: true
    permalink: /misc-projects/:name/

# Build settings
markdown: kramdown
# Don't set plugins because all of them are set in the jekyll_plugins
# group of the Gemfile

# Add extra files to exclude from processing.
exclude:
  - docker-compose.yml
  - postcss.config.js
  - package.json
  - package-lock.json

# Front Matter defaults
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/s8a-thumbnail.webp
