services:
  site:
    image: jvconseil/jekyll-docker:stable
    command: sh -c 'npm install && npm run build && jekyll serve --drafts'
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
      - NODE_ENV=development
      - TZ=America/Caracas
      - DEBUG=0
