- webdev:
  title: "Web development"
  features:
    - "Websites of different kinds: For businesses, people, products and others."
    - "High quality at a reasonable price."
    - "Modern, responsive web design."
    - "Optimised for fast loading."
    - "Database systems."
- video:
  title: "Video editing"
  features:
    - "Videos of different kinds: Family/school videos, short films, advertisements, etc."
    - "Great video and audio quality."
    - "Excellent transitions and effects."
    - "Adequate music selection."
    - "Different formats: MP4, AVI, MKV, OGV, etc."
