- webdev:
  title: Desarrollo de sitio web
  features:
    - "Sitios web de diversos fines: Para negocios, individuos, productos, entre otros."
    - "Alta calidad a precio razonable."
    - "Diseño moderno y adaptativo."
    - "Buena velocidad de carga."
    - "Sistemas de bases de datos."
- video:
  title: "Edición de vídeos"
  features:
    - "Vídeos de diferentes tipos: Recuerdos familiares/escolares, cortometrajes, publicidad, etc."
    - "Alta calidad de vídeo y audio."
    - "Transiciones y efectos profesionales."
    - "Selección adecuada de música."
    - "Diferentes formatos: MP4, AVI, MKV, OGV, etc."
