- id: "mrfbr"
  title: "Modified r/Fitness Basic Beginner Routine"
  general-info:
    - text: "Beginner level."
    - text: "For men."
    - text: "Original routine."
      url: https://thefitness.wiki/routines/r-fitness-basic-beginner-routine/
    - text: "Replaced exercises marked with asterisks."
    - text: "AMRAP means \"as many reps as possible.\""
  workouts:
    - id: "a"
      title: "Workout A"
      exercises:
        - name: "Barbell row"
          sets-reps: "3 sets, 5 reps, last set AMRAP."
          details:
            - text: "Guide at StrongLifts."
              url: https://stronglifts.com/barbell-row/
            - text: "Exercise information at ExRx."
              url: https://exrx.net/WeightExercises/BackGeneral/BBBentOverRow
        - name: "Push-up*"
          sets-reps: "3 sets, 10 reps, last set AMRAP."
          original-exercise:
            name: "Bench press"
            links:
              - text: "Nuckols"
                url: https://www.strongerbyscience.com/how-to-bench/
              - text: "StrongLifts"
                url: https://stronglifts.com/bench-press/
              - text: "ExRx"
                url: https://exrx.net/WeightExercises/PectoralSternal/BBBenchPress
          details:
            - text: "Guide by Nick Elorreaga."
              url: https://nick-e.com/push-up/
        - name: "Squat"
          sets-reps: "3 sets, 5 reps, last set AMRAP."
          alternative-exercises:
            - name: "Front squat"
              links:
                - text: "ExRx"
                  url: https://exrx.net/WeightExercises/Quadriceps/BBFrontSquat
            - name: "Hack squat"
              links:
                - text: "ExRx"
                  url: https://exrx.net/WeightExercises/Quadriceps/BBHackSquat
            - name: "Zercher squat"
              links:
                - text: "ExRx"
                  url: https://exrx.net/WeightExercises/Quadriceps/BBZercherSquat
          details:
            - text: "In-depth guide by Greg Nuckols."
              url: https://www.strongerbyscience.com/how-to-squat/
            - text: "Guide at StrongLifts."
              url: https://stronglifts.com/squat/
            - text: "Exercise information at ExRx"
              url: https://exrx.net/WeightExercises/Quadriceps/BBSquat
    - id: "b"
      title: "Workout B"
      exercises:
        - name: "Barbell row*"
          sets-reps: "3 sets, 5 reps, last set AMRAP."
          original-exercise:
            name: "Pull-up"
            links:
              - text: "Elorreaga"
                url: https://nick-e.com/pull-up/
              - text: "ExRx"
                url: https://exrx.net/WeightExercises/LatissimusDorsi/BWPullup
          details:
            - text: "Guide at StrongLifts."
              url: https://stronglifts.com/barbell-row/
            - text: "Exercise information at ExRx."
              url: https://exrx.net/WeightExercises/BackGeneral/BBBentOverRow
        - name: "Overhead press"
          sets-reps: "3 sets, 5 reps, last set AMRAP."
          details:
            - text: "Guide at StrongLifts."
              url: https://stronglifts.com/overhead-press/
            - text: "Exercise information at ExRx."
              url: https://exrx.net/WeightExercises/DeltoidAnterior/BBMilitaryPress
        - name: "Deadlift"
          sets-reps: "3 sets, 5 reps, last set AMRAP."
          details:
            - text: "In-depth guide by Greg Nuckols."
              url: https://www.strongerbyscience.com/how-to-deadlift/
            - text: "Guide at StrongLifts."
              url: https://stronglifts.com/deadlift/
            - text: "Exercise information at ExRx"
              url: https://exrx.net/WeightExercises/ErectorSpinae/BBDeadlift
- id: "mscw1t4"
  title: "Modified Strong Curves Weeks 1-4 routine"
  general-info:
    - text: "Beginner level."
    - text: "For women."
    - text: "Original routine in book by Bret Contreras and Kellie Davis."
      url: https://www.amazon.com/Strong-Curves-Womans-Building-Better/dp/1936608642
    - text: "Routine spreadsheet used as source."
      url: https://docs.google.com/spreadsheets/d/1ghaT_a63nwDIDNgSEmNWhVdWdeM9b8N4hD-kYEMd3Zg/edit#gid=1409917690
    - text: "Only two workouts (A and B) instead of three."
    - text: "Replaced exercises marked with asterisks."
  workouts:
    - id: "a"
      title: "Workout A"
      exercises:
        - name: "Glute bridge"
          sets-reps: "3 sets, 10 reps, last set 20 reps."
          details:
            - text: "Guide at Coach magazine."
              url: https://www.coachmag.co.uk/glute-exercises/2333/glute-bridge-how-to-do-it-benefits-and-variations
        - name: "Dumbbell row"
          sets-reps: "3 sets, 8 reps each side, last set 12 reps each side."
          details:
            - text: "Exercise information at ExRx."
              url: https://exrx.net/WeightExercises/BackGeneral/DBBentOverRow
        - name: "Weighted front squat*"
          sets-reps: "3 sets, 10 reps, last set 20 reps."
          original-exercise:
            name: "Box squat"
            links:
              - text: "ExRx"
                url: https://exrx.net/WeightExercises/GluteusMaximus/BBBoxSquat
          details:
            - text: "Exercise information at ExRx."
              url: https://exrx.net/WeightExercises/GluteusMaximus/WTFrontSquat
        - name: "Incline push-up*"
          sets-reps: "3 sets, 8 reps, last set 12 reps."
          original-exercise:
            name: "Dumbbell bench press"
            links:
              - text: "ExRx"
                url: https://exrx.net/WeightExercises/PectoralSternal/DBBenchPress
          details:
            - text: "Exercise information at ExRx."
              url: https://exrx.net/WeightExercises/PectoralSternal/BWInclinePushup
        - name: "Romanian deadlift"
          sets-reps: "3 sets, 10 reps, last set 20 reps."
          details:
            - text: "Exercise information at ExRx."
              url: https://exrx.net/WeightExercises/OlympicLifts/RomanianDeadlift
        - name: "Side lying hip abduction"
          sets-reps: "1 set, 30 reps each side."
          details:
            - text: "Guide at VeryWell Fit."
              url: https://www.verywellfit.com/side-lying-hip-abductions-techniques-benefits-variations-4783963
    - id: "b"
      title: "Workout B"
      exercises:
        - name: "Single leg hip bridge"
          sets-reps: "3 sets, 10 reps each side, last set 20 reps each side."
          details:
            - text: "Exercise information at ExRx."
              url: https://exrx.net/WeightExercises/GluteusMaximus/BWLyingHipExtension
        - name: "Dumbbell row*"
          sets-reps: "3 sets, 8 reps each side, last set 12 reps each side."
          original-exercise:
            name: "Lat pulldown"
            links:
              - text: "ExRx"
                url: https://exrx.net/WeightExercises/LatissimusDorsi/CBFrontPulldown
          details:
            - text: "Exercise information at ExRx."
              url: https://exrx.net/WeightExercises/BackGeneral/DBBentOverRow
        - name: "Dumbbell step-up"
          sets-reps: "3 sets, 10 reps each side, last set 20 reps each side."
          details:
            - text: "Exercise information at ExRx."
              url: https://exrx.net/WeightExercises/Quadriceps/DBStepUp
        - name: "Dumbbell shoulder press"
          sets-reps: "3 sets, 8 reps, last set 12 reps."
          details:
            - text: "Exercise information at ExRx."
              url: https://exrx.net/WeightExercises/DeltoidAnterior/DBShoulderPress
        - name: "Bird dog*"
          sets-reps: "3 sets, 10 reps, last set 20 reps."
          original-exercise:
            name: "Barbell 45° back extension"
            links:
              - text: "ExRx"
                url: https://exrx.net/WeightExercises/ErectorSpinae/BB45BackExtension
          details:
            - text: "Exercise information at ExRx."
              url: https://exrx.net/WeightExercises/ErectorSpinae/BWBirdDog
        - name: "Side lying hip abduction*"
          sets-reps: "1 set, 30 reps each side."
          original-exercise:
            name: "Side lying clam"
            links:
              - text: "Spear Center"
                url: https://spearcenter.com/backtolife-exercise-side-lying-clam-shells/
          details:
            - text: "Guide at VeryWell Fit."
              url: https://www.verywellfit.com/side-lying-hip-abductions-techniques-benefits-variations-4783963
